### PR TITLE
Update zustand to 4.3.2, update types, update dev dependencies

### PR DESCRIPTION
**Pull request by konclave**
Main change was updating `zustand` to 4.3.2 and align typing with it. 
Also update other dev dependencies.

### CODE REVIEW

**Comment by konclave** [comment]
@cmlarsen could you please check review and merge this PR?

**Comment by konclave** [comment]
@cmlarsen could you also publish the new package version to npm registry?

**Comment by cmlarsen** [comment]
done!

**Comment by resdevd** [comment]
Since yesterday, our production deployments are failing with error - "/bin/sh: husky: command not found" with this package
Could this pr be the reason?

**Comment by konclave** [comment]
Yes, it is. Because as I see, all the files including .git folder were published to the npm without any cleanup.

**Comment by konclave** [comment]
@cmlarsen seems like instead of publishing the contents of the dist folder, you've published all the sources that are in the repository. Could you please publish the package one more time with the dist folder content only?

**Comment by cmlarsen** [comment]
Lol. Yeah sorry. I was doing to many things at once.

**Pull request merged**
